language: cpp

# Use Ubuntu Xenial (16.04) environment.
dist: xenial

addons:
  apt:
    packages:
    - libxml2-dev
    - flex
    - bison
    - pkg-config
    # Optional dependency needed by hwtest
    - libpciaccess-dev
    # Optional dependency needed by demmt
    - libdrm-dev
    - libseccomp-dev
    # Optional dependency needed by nva
    - libpciaccess-dev
    - libx11-dev
    - libxext-dev
    - python3-dev
    - cython3
    # Optional dependencies needed by vdpow
    - libpciaccess-dev
    - libx11-dev
    - libvdpau-dev

env:
  global:
    - MAKEFLAGS="-j2"

compiler:
  - clang
  - gcc

script:
  - cmake .
  - make
  - make test
