language: cpp

# We need to use sudo because of Docker
sudo: require

compiler:
  - clang
  - gcc

services: docker

before_install:
  - docker build -t envytools -f Dockerfile .

script:
  - docker run -v `pwd`:/build envytools
    sh -c "
      export CXX=$CXX &&
      export CC=$CC &&
      $CC --version &&
      cmake . &&
      make &&
      make test
    "
